name: wannier-berri-org-html

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wannierberri
        pip install sphinx sphinx-rtd-theme sphinx-pyreverse nbsphinx sphinx_sitemap
        set -ev
        sudo apt-get install pdf2svg
        sudo wget https://github.com/jgm/pandoc/releases/download/1.15.1/pandoc-1.15.1-1-amd64.deb
        sudo dpkg -i pandoc-1.15.1-1-amd64.deb
    - name: make
      run: |
        make
